name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
          
      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v4
        
      - name: Install dependencies
        run: |
          luarocks install luacheck
          
      - name: Run Luacheck
        run: luacheck .