name: Lua Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: Kampfkarren/selene-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: selene.toml